### ISSUE TITLE
Some error when do imputation

### ISSUE THREAD

**Issue by xiekunwhy** [dellaporta-laboratory/LB-Impute#1]
Hi, Stephen Dellaporta,
Do you know what's wrong when getting error like follows?
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at imputation.GetProbabilities.getprobabilities(GetProbabilities.java:35)
	at imputation.ImputeBySample.imputebysample(ImputeBySample.java:57)
	at imputation.Impute.impute(Impute.java:67)
	at imputation.ImputeMain.start(ImputeMain.java:97)
	at imputation.ImputeMain.main(ImputeMain.java:34)

**Comment by dellaporta-laboratory** [comment]
Let me ask the lab and get back to you.

**Comment by dellaporta-laboratory** [comment]
That issue normally occurs when the file format isn't entirely compatible with LB-Impute. Would you post a few lines of your VCF file so I can confirm this?

**Comment by xiekunwhy** [comment]
Hi,
Sorry for replying so late.
Here is my vcf file. I'm not sure what's wrong with it.
[scaffold105.vcf.txt](https://github.com/dellaporta-laboratory/LB-Impute/files/638676/scaffold105.vcf.txt)

Best wishes!

**Comment by qgao2** [comment]
Hi Stephen,
Thanks for sharing this nice software!
I know this is an old post, but I got the similar error as @xiekunwhy when I tried to do imputation with LB-impute. My vcf file is v4.2, I have checked the example data, but still not sure what's the exact format LB-impute will take. 
Could you please help me, thanks a lot!

===================================================================
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
	at imputation.RetrieveParentals.retrieveparentals(RetrieveParentals.java:22)
	at imputation.ImputeBySample.imputebysample(ImputeBySample.java:43)
	at imputation.Impute.impute(Impute.java:54)
	at imputation.ImputeMain.start(ImputeMain.java:97)
	at imputation.ImputeMain.main(ImputeMain.java:34)

**Comment by klotzor** [comment]
I could solve the issue from the first post by removing genotytpes from the query file that do not match the reference file using conform-gt. Now I get the same error as qgao2.

Any suggestions from the developers?
