### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by IdoBar** [dellaporta-laboratory/LB-Impute#2]
Hi there,

I'm trying to impute genotypes from a `.vcf` file (v4.2 from Stacks) and I get the following error (not very informative):

```
java -jar ..\..\mapping_tools\LB-Impute.jar -method impute -f gstacks_no
_RL_Homo_pol_GATK.vcf -window 7 -o gstacks_no_RL_Homo_pol_imputed.vcf -parents ILL6002_RF,ILL7537_RF -parentimpute
```
That's the output:
```
Imputing sequence 9
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at imputation.ImputeBySample.imputebysample(ImputeBySample.java:31)
        at imputation.Impute.impute(Impute.java:54)
        at imputation.ImputeMain.start(ImputeMain.java:97)
        at imputation.ImputeMain.main(ImputeMain.java:34)
```
I guess it has to do with the `.vcf` format, but I have no idea what can it be.
See [example](https://drive.google.com/open?id=1LT81k5FuyF_RlCNmyDOQ7zvWQQTXb2v4) input file.
Any ideas?

**Comment by asifzubair** [comment]
Getting the same error. were you able to resolve it, @IdoBar ? Thanks! 

a.
