### ISSUE TITLE
IndexOutOfBoundsException error

### ISSUE THREAD

**Issue by shiyi-pan** [dellaporta-laboratory/LB-Impute#4]
Hi, I want to use the LB-Impute to impute my genotypes , but when I test it with the following script, I got an error:

java -jar LB-Impute.jar -method impute -f /ds3512/home/panyp/NN1138-2/16.QTL/05.test/LB-Impute/example_data/simulated_data/F1BC1/Coveragemodifiedvalues_chrl1 00000000_scount200_ptypef1bc1_vcount10000_mrec3_stdrec2_reads10000_rep1.vcf.gz -readerr 0.05 -genotypeerr 0.05 -recombdist 10000000 -window 5 -offspringimpute -parents par1,par2 -o outputvcf.vcf

and here is the error :

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at imputation.Impute.impute(Impute.java:41)
        at imputation.ImputeMain.start(ImputeMain.java:97)
        at imputation.ImputeMain.main(ImputeMain.java:34)

could you help me fix it ? Thank you very much.

**Comment by aliceboizet** [comment]
I got the same error and realized this was because the program reads .vcf file and not .vcf.gz. So you have to unzip the testing files before running the program.
